import{MAPS,getMap,FACTIONS,NODE_TYPES}from'./maps.js';
import{DominionEngine}from'./engine.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#battlefield'),ctx=canvas.getContext('2d',{alpha:true});
const dom={home:$('#homeOverlay'),result:$('#resultOverlay'),pause:$('#pauseOverlay'),levelGrid:$('#levelGrid'),sector:$('#sectorStat'),energy:$('#energyStat'),time:$('#timeStat'),missionTitle:$('#missionTitle'),missionCopy:$('#missionCopy'),difficulty:$('#difficultyChip'),objectives:$('#objectiveList'),selected:$('#selectedCard'),bars:$('#factionBars'),threat:$('#threatLabel'),log:$('#combatLog'),notices:$('#notificationStack'),resultTitle:$('#resultTitle'),resultKicker:$('#resultKicker'),resultStars:$('#resultStars'),resultStats:$('#resultStats'),profileStars:$('#profileStars'),profileProgress:$('#profileProgress'),dragLabel:$('#dragLabel')};
let engine=null,currentMap=null,selectedId=null,dragFrom=null,pointerWorld=null,armedAbility=null,last=performance.now(),lastUI=0,lastEvents=0,resultShown=false,soundEnabled=true,audio=null;
let camera={zoom:1,x:0,y:0};let viewport={scale:1,ox:0,oy:0,w:1200,h:720};let pan=null,pointers=new Map(),pinch=null;
const profile=loadProfile();
const particles=Array.from({length:80},(_,i)=>({x:(i*137)%1200,y:(i*251)%720,r:.5+(i%4)*.25,a:.08+(i%5)*.025}));
renderCampaign();bindUI();resize();requestAnimationFrame(loop);window.addEventListener('resize',resize);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
function loadProfile(){try{return{stars:0,completed:{},...JSON.parse(localStorage.getItem('neon-dominion-profile')||'{}')}}catch{return{stars:0,completed:{}}}}
function saveProfile(){localStorage.setItem('neon-dominion-profile',JSON.stringify(profile))}
function bindUI(){
 $('#campaignBtn').onclick=()=>startLevel(firstUnlocked());$('#quickBtn').onclick=()=>startLevel(MAPS[Math.floor(Math.random()*MAPS.length)].id,{quick:true});
 $('#soundBtn').onclick=()=>{soundEnabled=!soundEnabled;$('#soundBtn').textContent=soundEnabled?'◉':'○';beep(520,.05)};
 $('#pauseBtn').onclick=()=>togglePause();$('#menuBtn').onclick=()=>{if(engine){engine.speed=0;dom.pause.classList.add('visible')}};$('#resumeBtn').onclick=()=>resume();$('#exitBtn').onclick=()=>goHome();
 $('#retryBtn').onclick=()=>startLevel(currentMap.id);$('#nextBtn').onclick=()=>{const next=MAPS[currentMap.order]||null;next?startLevel(next.id):goHome()};$('#clearLogBtn').onclick=()=>dom.log.innerHTML='';
 $$('.speed-control button').forEach(b=>b.onclick=()=>setSpeed(+b.dataset.speed));
 $$('.ability').forEach(b=>b.onclick=()=>activateAbility(b.dataset.ability));
 $('#mobilePanelToggle').onclick=()=>document.body.classList.toggle('show-right');document.addEventListener('keydown',e=>{if(e.code==='Space'&&engine){e.preventDefault();togglePause()}if(e.code==='Escape'){armedAbility=null;syncAbilities();document.body.classList.remove('show-left','show-right')}});
 canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('wheel',wheel,{passive:false});
}
function renderCampaign(){const unlocked=Math.max(1,Object.keys(profile.completed).length+1);dom.levelGrid.innerHTML=MAPS.map(m=>{const stars=profile.completed[m.id]||0;return`<button class="level-card" data-level="${m.id}" ${m.order>unlocked?'disabled':''}><span class="level-num">ОПЕРАЦИЯ 0${m.order}</span><b>${m.title}</b><small>${m.subtitle} · ${m.difficulty}</small><span class="level-stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</span></button>`}).join('');$$('[data-level]').forEach(b=>b.onclick=()=>startLevel(b.dataset.level));const total=Object.values(profile.completed).reduce((a,b)=>a+b,0);profile.stars=total;dom.profileStars.textContent=`${total} / 18 ★`;dom.profileProgress.style.width=`${total/18*100}%`}
function firstUnlocked(){return MAPS.find(m=>!profile.completed[m.id])?.id||MAPS[MAPS.length-1].id}
function startLevel(id,options={}){currentMap=getMap(id);engine=new DominionEngine(currentMap,{difficulty:currentMap.order<2?.75:currentMap.order<4?1.05:1.35,seed:options.quick?Date.now():undefined});selectedId=engine.factionNodes('player')[0]?.id||null;armedAbility=null;camera={zoom:1,x:0,y:0};resultShown=false;dom.home.classList.remove('visible');dom.result.classList.remove('visible');dom.pause.classList.remove('visible');document.body.classList.remove('show-left','show-right');dom.missionTitle.textContent=currentMap.title;dom.missionCopy.textContent=currentMap.description;dom.difficulty.textContent=currentMap.difficulty;dom.objectives.innerHTML=currentMap.objectives.map(x=>`<div class="objective">${x}</div>`).join('');dom.log.innerHTML='';log(`Операция «${currentMap.title}» началась`);notice('Система готова. Проведите от своего сектора к цели.','good');setSpeed(1);resize();syncUI(true);beep(290,.12)}
function goHome(){engine=null;currentMap=null;dom.pause.classList.remove('visible');dom.result.classList.remove('visible');dom.home.classList.add('visible');renderCampaign()}
function setSpeed(speed){if(!engine)return;engine.speed=speed;$$('.speed-control button').forEach(b=>b.classList.toggle('active',+b.dataset.speed===speed));$('#pauseBtn').textContent=speed===0?'▶':'Ⅱ'}
function togglePause(){if(!engine)return;if(engine.speed===0)resume();else{engine.speed=0;dom.pause.classList.add('visible')}}
function resume(){dom.pause.classList.remove('visible');setSpeed(1)}
function activateAbility(type){if(!engine)return;if(type==='strike'){armedAbility=armedAbility==='strike'?null:'strike';syncAbilities();notice(armedAbility?'Выберите вражеский сектор для импульса':'Импульс отменён');return}const target=selectedId;if(engine.useAbility(type,target)){beep(type==='overdrive'?760:620,.12);notice('Способность активирована','good');syncUI(true)}else notice('Недостаточно энергии или неверная цель','bad')}
function pointerDown(e){if(!engine||engine.speed===0)return;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const p=screenToWorld(e.clientX,e.clientY);pointerWorld=p;const hit=hitNode(p);
 if(pointers.size===2){const vals=[...pointers.values()];pinch={distance:Math.hypot(vals[0].x-vals[1].x,vals[0].y-vals[1].y),zoom:camera.zoom};dragFrom=null;return}
 if(armedAbility==='strike'&&hit){if(engine.useAbility('strike',hit.id)){armedAbility=null;syncAbilities();beep(150,.18);notice('Импульс нанесён','good')}else notice('Нужна вражеская цель и 50 энергии','bad');return}
 if(hit?.owner==='player'){selectedId=hit.id;dragFrom=hit.id;beep(430,.035);syncSelected()}else{pan={sx:e.clientX,sy:e.clientY,x:camera.x,y:camera.y};selectedId=hit?.id||selectedId;syncSelected()}}
function pointerMove(e){if(!engine)return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&pointers.size>=2){const vals=[...pointers.values()];const d=Math.hypot(vals[0].x-vals[1].x,vals[0].y-vals[1].y);camera.zoom=Math.max(1,Math.min(1.8,pinch.zoom*d/pinch.distance));return}pointerWorld=screenToWorld(e.clientX,e.clientY);if(pan&&old){camera.x=pan.x+(e.clientX-pan.sx)/viewport.scale/camera.zoom;camera.y=pan.y+(e.clientY-pan.sy)/viewport.scale/camera.zoom;clampCamera()}if(dragFrom){const hit=hitNode(pointerWorld);dom.dragLabel.style.display='block';dom.dragLabel.style.left=`${e.offsetX+12}px`;dom.dragLabel.style.top=`${e.offsetY+12}px`;dom.dragLabel.textContent=hit&&engine.connected(dragFrom,hit.id)?`${engine.nodes[dragFrom].id} → ${hit.id}`:'ВЫБЕРИТЕ СВЯЗАННЫЙ УЗЕЛ'}}
function pointerUp(e){if(!engine)return;const p=screenToWorld(e.clientX,e.clientY);const target=hitNode(p);if(dragFrom&&target&&target.id!==dragFrom){const ok=engine.send(dragFrom,target.id,.52,'player');if(ok){beep(560,.055);log(`Отряд направлен: ${dragFrom} → ${target.id}`)}else notice('Секторы не соединены или недостаточно сил','bad')}dragFrom=null;pan=null;pinch=null;pointers.delete(e.pointerId);dom.dragLabel.style.display='none'}
function wheel(e){if(!engine)return;e.preventDefault();const before=screenToWorld(e.clientX,e.clientY);camera.zoom=Math.max(1,Math.min(1.8,camera.zoom*(e.deltaY<0?1.12:.89)));const after=screenToWorld(e.clientX,e.clientY);camera.x+=after.x-before.x;camera.y+=after.y-before.y;clampCamera()}
function clampCamera(){const limX=(camera.zoom-1)*340/camera.zoom,limY=(camera.zoom-1)*210/camera.zoom;camera.x=Math.max(-limX,Math.min(limX,camera.x));camera.y=Math.max(-limY,Math.min(limY,camera.y))}
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);const scale=Math.min(r.width/1200,r.height/720);viewport={scale,ox:(r.width-1200*scale)/2,oy:(r.height-720*scale)/2,w:r.width,h:r.height}}
function screenToWorld(cx,cy){const r=canvas.getBoundingClientRect();let x=(cx-r.left-viewport.ox)/viewport.scale,y=(cy-r.top-viewport.oy)/viewport.scale;x=(x-600)/camera.zoom+600-camera.x;y=(y-360)/camera.zoom+360-camera.y;return{x,y}}
function hitNode(p){if(!engine)return null;let best=null,bd=Infinity;for(const n of Object.values(engine.nodes)){const d=Math.hypot(p.x-n.x,p.y-n.y),r=NODE_TYPES[n.type].radius+9;if(d<r&&d<bd){best=n;bd=d}}return best}
function loop(now){const dt=(now-last)/1000;last=now;if(engine){engine.update(dt);if(now-lastUI>130){syncUI();lastUI=now}drainEvents();if(engine.result&&!resultShown)showResult()}render(now);requestAnimationFrame(loop)}
function render(now){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.save();ctx.translate(viewport.ox,viewport.oy);ctx.scale(viewport.scale,viewport.scale);ctx.translate(600,360);ctx.scale(camera.zoom,camera.zoom);ctx.translate(-600+camera.x,-360+camera.y);drawBackground(now);if(engine){drawLinks();drawConvoys(now);drawNodes(now);drawEffects();if(dragFrom&&pointerWorld)drawDrag()};ctx.restore()}
function drawBackground(now){ctx.fillStyle='#050711';ctx.fillRect(-300,-200,1800,1120);ctx.strokeStyle='rgba(84,245,255,.028)';ctx.lineWidth=1/camera.zoom;for(let x=0;x<=1200;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,720);ctx.stroke()}for(let y=0;y<=720;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1200,y);ctx.stroke()}for(const p of particles){const pulse=.65+.35*Math.sin(now*.0007+p.x);ctx.globalAlpha=p.a*pulse;ctx.fillStyle='#8edcff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawLinks(){for(const[a,b]of engine.links){const x=engine.nodes[a],y=engine.nodes[b];const grad=ctx.createLinearGradient(x.x,x.y,y.x,y.y);grad.addColorStop(0,FACTIONS[x.owner].color+'45');grad.addColorStop(1,FACTIONS[y.owner].color+'45');ctx.strokeStyle=grad;ctx.lineWidth=2;ctx.setLineDash([5,9]);ctx.lineDashOffset=-engine.time*8;ctx.beginPath();ctx.moveTo(x.x,x.y);ctx.lineTo(y.x,y.y);ctx.stroke();ctx.setLineDash([])}}
function drawNodes(now){for(const n of Object.values(engine.nodes)){const cfg=NODE_TYPES[n.type],f=FACTIONS[n.owner],selected=n.id===selectedId,pulse=1+Math.sin(now*.003+n.x)*.025;ctx.save();ctx.translate(n.x,n.y);ctx.scale(pulse,pulse);ctx.shadowColor=f.color;ctx.shadowBlur=n.owner==='neutral'?8:selected?30:18;ctx.fillStyle='rgba(5,8,16,.96)';ctx.strokeStyle=f.color;ctx.lineWidth=selected?4:2.2;ctx.beginPath();polygon(0,0,cfg.radius,n.type==='fortress'?6:8,Math.PI/8);ctx.fill();ctx.stroke();ctx.shadowBlur=0;const ratio=n.troops/engine.capacity(n);ctx.strokeStyle=f.color;ctx.globalAlpha=.23;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,cfg.radius+7,-Math.PI/2,Math.PI*1.5);ctx.stroke();ctx.globalAlpha=1;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,cfg.radius+7,-Math.PI/2,-Math.PI/2+Math.PI*2*ratio);ctx.stroke();if(n.shieldUntil>engine.time){ctx.strokeStyle='#ffffff';ctx.globalAlpha=.45+.2*Math.sin(now*.008);ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,cfg.radius+13,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 15px Inter, sans-serif';ctx.fillText(Math.floor(n.troops),0,0);ctx.fillStyle=f.color;ctx.font='800 8px Inter, sans-serif';ctx.fillText(cfg.name.toUpperCase(),0,cfg.radius+21);ctx.restore()}}
function drawConvoys(now){for(const c of engine.convoys){const a=engine.nodes[c.from],b=engine.nodes[c.to],t=c.progress,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t,ang=Math.atan2(b.y-a.y,b.x-a.x);ctx.save();ctx.translate(x,y);ctx.rotate(ang);ctx.shadowColor=FACTIONS[c.owner].color;ctx.shadowBlur=14;ctx.fillStyle=FACTIONS[c.owner].color;ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(-6,-5);ctx.lineTo(-3,0);ctx.lineTo(-6,5);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font='700 8px Inter';ctx.textAlign='center';ctx.fillText(c.amount,0,-10);ctx.restore()}}
function drawEffects(){for(const e of engine.effects){ctx.strokeStyle=`rgba(255,255,255,${e.life})`;ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,(1-e.life)*70+10,0,Math.PI*2);ctx.stroke()}}
function drawDrag(){const a=engine.nodes[dragFrom];ctx.strokeStyle='#54f5ff';ctx.lineWidth=3;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(pointerWorld.x,pointerWorld.y);ctx.stroke();ctx.setLineDash([])}
function polygon(x,y,r,sides,rot=0){for(let i=0;i<sides;i++){const a=rot+i*Math.PI*2/sides,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}
function syncUI(force=false){if(!engine)return;const owned=engine.factionNodes('player').length,total=Object.keys(engine.nodes).length;dom.sector.textContent=`${owned} / ${total}`;dom.energy.textContent=Math.floor(engine.energy);dom.time.textContent=formatTime(engine.time);syncSelected();syncAbilities();syncBars();const enemy=engine.factionPower('red')+engine.factionPower('violet'),player=engine.factionPower('player');dom.threat.textContent=enemy>player*1.35?'КРИТИЧНО':enemy>player*.8?'НАПРЯЖЁННО':'СТАБИЛЬНО';dom.threat.style.color=enemy>player*1.35?'#ff5578':enemy>player*.8?'#ffd66b':'#58f2a5'}
function syncSelected(){if(!engine)return;const n=engine.nodes[selectedId];if(!n){dom.selected.innerHTML='<div class="selected-empty">Выберите сектор</div>';return}const cfg=NODE_TYPES[n.type],owner=FACTIONS[n.owner];dom.selected.innerHTML=`<div class="selected-head"><b>${n.id.toUpperCase()}</b><span class="selected-type" style="color:${owner.color}">${owner.name}</span></div><div class="selected-number">${Math.floor(n.troops)}</div><div class="selected-meta"><span>${cfg.name}</span><span>Прирост +${cfg.growth.toFixed(1)}/с</span></div>`}
function syncAbilities(){$$('.ability').forEach(b=>{const costs={shield:35,overdrive:60,strike:50,surge:75};b.disabled=!engine||engine.energy<costs[b.dataset.ability];b.classList.toggle('armed',armedAbility===b.dataset.ability)})}
function syncBars(){const powers=['player','red','violet'].map(id=>({id,p:engine.factionPower(id)})),max=Math.max(1,...powers.map(x=>x.p));dom.bars.innerHTML=powers.map(x=>`<div class="faction-row"><span>${FACTIONS[x.id].name}</span><div class="faction-track"><i style="width:${x.p/max*100}%;background:${FACTIONS[x.id].color}"></i></div><b>${Math.round(x.p)}</b></div>`).join('')}
function drainEvents(){while(lastEvents<engine.events.length){const e=engine.events[lastEvents++];log(e.text);notice(e.text,e.type);if(e.type==='bad')beep(130,.1)}}
function log(text){const el=document.createElement('div');el.className='log-item';el.textContent=`${engine?formatTime(engine.time):'00:00'} · ${text}`;dom.log.prepend(el);while(dom.log.children.length>14)dom.log.lastChild.remove()}
function notice(text,type=''){const el=document.createElement('div');el.className=`notice ${type}`;el.textContent=text;dom.notices.append(el);setTimeout(()=>el.remove(),2600)}
function showResult(){resultShown=true;setSpeed(0);const victory=engine.result==='victory',stars=victory?calcStars():0;dom.resultKicker.textContent=victory?'ОПЕРАЦИЯ ЗАВЕРШЕНА':'СЕТЬ ПОТЕРЯНА';dom.resultTitle.textContent=victory?'ПОБЕДА':'ПОРАЖЕНИЕ';dom.resultTitle.style.color=victory?'#54f5ff':'#ff5578';dom.resultStars.textContent=victory?`${'★'.repeat(stars)}${'☆'.repeat(3-stars)}`:'✕';dom.resultStats.innerHTML=`<div class="result-stat"><span>ВРЕМЯ</span><strong>${formatTime(engine.time)}</strong></div><div class="result-stat"><span>ЗАХВАЧЕНО</span><strong>${engine.stats.captured}</strong></div><div class="result-stat"><span>РЕПУТАЦИЯ</span><strong>${Math.round(engine.reputation)}%</strong></div>`;if(victory){profile.completed[currentMap.id]=Math.max(profile.completed[currentMap.id]||0,stars);saveProfile();beep(820,.25)}else beep(100,.28);dom.result.classList.add('visible')}
function calcStars(){let stars=1;if(engine.time<=currentMap.parTime)stars++;if(engine.reputation>=75&&engine.stats.lost<=3)stars++;return stars}
function formatTime(s){const m=Math.floor(s/60),sec=Math.floor(s%60);return`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function beep(freq=440,duration=.06){if(!soundEnabled)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
window.NeonDominionQA={startLevel:(id='awakening')=>startLevel(id),getState:()=>engine?.snapshot()||null,send:(a,b,r=.5)=>engine?.send(a,b,r,'player'),ability:(t,id)=>engine?.useAbility(t,id),setSpeed:s=>setSpeed(s),maps:MAPS.map(m=>m.id)};
