'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='aurora-eleven-save-v2';
const basePlayers=[
['Илья Волков','GK',81,27,96,8.1],['Максим Орлов','GK',73,23,89,3.2],['Даниил Белов','LB',77,24,91,5.9],['Артём Соколов','CB',80,28,86,7.8],['Кирилл Громов','CB',79,25,93,7],['Роман Титов','RB',78,26,88,6.4],['Егор Фомин','CB',73,21,97,4.4],['Андрей Жуков','LB',71,30,79,2.1],['Никита Морозов','DM',79,27,92,7.1],['Михаил Лебедев','CM',82,25,90,10.4],['Вадим Крылов','CM',77,22,96,6.2],['Сергей Данилов','AM',80,24,84,9.6],['Матвей Панов','CM',72,20,98,3.7],['Олег Котов','RM',74,29,83,4],['Алексей Захаров','LW',83,25,88,12.6],['Денис Романов','ST',84,27,85,15.2],['Илья Макаров','RW',81,23,94,11.7],['Артём Сафонов','ST',75,21,97,6]
];
const posGroup=p=>p==='GK'?'GK':['LB','CB','RB','LWB','RWB'].includes(p)?'DEF':['DM','CM','AM','LM','RM'].includes(p)?'MID':'FWD';
const table=[['Север',39],['Атлетик',36],['Столица',34],['Аврора',31],['Рубеж',28],['Олимп',26],['Вектор',24],['Метеор',23]];
const formations={
'4-3-3':[['GK',50,91],['LB',14,72],['CB',37,75],['CB',63,75],['RB',86,72],['CM',28,48],['DM',50,55],['CM',72,48],['LW',20,22],['ST',50,15],['RW',80,22]],
'4-2-3-1':[['GK',50,91],['LB',14,72],['CB',37,76],['CB',63,76],['RB',86,72],['DM',37,56],['DM',63,56],['LW',18,34],['AM',50,38],['RW',82,34],['ST',50,15]],
'3-5-2':[['GK',50,91],['CB',25,74],['CB',50,77],['CB',75,74],['LWB',12,49],['CM',34,50],['DM',50,57],['CM',66,50],['RWB',88,49],['ST',38,19],['ST',62,19]]};
const defaults=()=>({money:28.4,fans:42680,rating:1284,formation:'4-3-3',mentality:52,pressing:62,tempo:68,instructions:['short','wide'],trained:false,players:basePlayers.map((p,i)=>({id:i+1,name:p[0],position:p[1],rating:p[2],age:p[3],energy:p[4],value:p[5]})),market:[],activity:[['↗','Рост формы команды','Тренировка дала +2 к готовности','18 мин'],['★','Захаров — игрок тура','Два гола и результативная передача','2 ч'],['₽','Новый спонсорский бонус','На счёт клуба поступило ₽1,2 млн','Вчера']]});
let state=load(),filter='ALL',match=createMatch(),timer=null,raf=null,toastTimer=null;
function load(){try{return{...defaults(),...JSON.parse(localStorage.getItem(KEY)||'null')}}catch{return defaults()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function money(v){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(v)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2300)}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#sidebar').classList.remove('open');if(id==='match')draw(false)}
$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('.jump').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#burger').onclick=()=>$('#sidebar').classList.toggle('open');
function renderHeader(){$('#money').textContent=`₽ ${money(state.money)} млн`;$('#fans').textContent=money(state.fans);$('#rating').textContent=money(state.rating);const best=[...state.players].sort((a,b)=>b.rating-a.rating).slice(0,11);$('#power').textContent=Math.round(best.reduce((s,p)=>s+p.rating,0)/11)}
function renderTable(){$('#table').innerHTML=table.map((r,i)=>`<div class="standing ${r[0]==='Аврора'?'ours':''}"><span>${i+1}</span><b>${r[0]}</b><span>17</span><span>${Math.max(0,12-i)}</span><strong>${r[1]}</strong></div>`).join('')}
function renderActivity(){$('#activity').innerHTML=state.activity.slice(0,5).map(a=>`<div class="activity-item"><span>${a[0]}</span><div><b>${a[1]}</b><p>${a[2]}</p></div><time>${a[3]}</time></div>`).join('')}
function renderPlayers(){const q=$('#search').value.toLowerCase();const arr=state.players.filter(p=>(filter==='ALL'||posGroup(p.position)===filter)&&p.name.toLowerCase().includes(q));$('#players').innerHTML=arr.map(p=>`<div class="player-row"><div class="player-name"><span class="avatar">${p.name.split(' ').map(x=>x[0]).join('')}</span><div><b>${p.name}</b><small style="display:block;color:#738b7e;margin-top:3px">${p.position}</small></div></div><span class="pos">${p.position}</span><span class="rating-pill">${p.rating}</span><span><b>${p.energy}%</b><div class="energy"><i style="width:${p.energy}%"></i></div></span><span>${p.age}</span><b>₽ ${money(p.value)} млн</b></div>`).join('')||'<p style="padding:25px;color:#8ea79a">Игроки не найдены</p>'}
function pick(pos,used){let group=posGroup(pos);let options=state.players.filter(p=>!used.has(p.id)&&(p.position===pos||posGroup(p.position)===group)).sort((a,b)=>b.rating-a.rating);const p=options[0]||state.players.find(p=>!used.has(p.id));used.add(p.id);return p}
function renderPitch(){const used=new Set();$('#pitch').querySelectorAll('.pitch-player').forEach(x=>x.remove());formations[state.formation].forEach(([pos,x,y])=>{const p=pick(pos,used),e=document.createElement('div');e.className='pitch-player';e.style.left=x+'%';e.style.top=y+'%';e.innerHTML=`<i>${p.rating}</i><span>${p.name.split(' ')[1]}</span>`;$('#pitch').appendChild(e)});$('#formation').value=state.formation;updateReadiness()}
function label(v,kind){if(kind==='mentality')return v<35?'Осторожно':v>67?'Атакующая':'Сбалансированно';if(kind==='pressing')return v<35?'Низкий':v>67?'Высокий':'Средний';return v<35?'Медленный':v>67?'Быстрый':'Средний'}
function updateReadiness(){['mentality','pressing','tempo'].forEach(id=>{state[id]=+$(`#${id}`).value;$(`#${id}Text`).textContent=label(state[id],id)});const score=Math.max(60,Math.min(98,Math.round(72+(state.pressing+state.tempo)/18+state.instructions.length*2-Math.abs(state.mentality-55)/8)));$('#readiness').textContent=score;$('#readyBar').style.width=score+'%'}
function marketPlayer(i){const names=['Тимур Барсов','Леон Власов','Давид Северин','Марк Велин','Ян Орехов','Руслан Миронов','Антон Градов','Эмиль Ларин'];const positions=['ST','CM','CB','RW','DM','LB'];const rating=72+Math.floor(Math.random()*14);return{id:Date.now()+i,name:names[(i+Math.floor(Math.random()*names.length))%names.length],position:positions[Math.floor(Math.random()*positions.length)],rating,age:19+Math.floor(Math.random()*10),energy:95,value:+(3.5+(rating-70)*.9+Math.random()*3).toFixed(1)}}
function generateMarket(){state.market=Array.from({length:6},(_,i)=>marketPlayer(i));save()}
function renderMarket(){if(!state.market.length)generateMarket();$('#marketGrid').innerHTML=state.market.map(p=>`<article class="market-card"><div class="top"><span class="pos">${p.position}</span><span class="rating-pill">${p.rating}</span></div><h3>${p.name}</h3><p>Потенциал: ${Math.min(92,p.rating+5)} · форма отличная</p><div class="details"><div><small>ВОЗРАСТ</small><b>${p.age}</b></div><div><small>ЭНЕРГИЯ</small><b>${p.energy}%</b></div><div><small>ЦЕНА</small><b>${money(p.value)}</b></div></div><button class="primary buy" data-id="${p.id}">Купить · ₽${money(p.value)} млн</button></article>`).join('');$$('.buy').forEach(b=>b.onclick=()=>buy(+b.dataset.id))}
function buy(id){const p=state.market.find(x=>x.id===id);if(!p)return;if(state.money<p.value)return toast('Недостаточно средств');state.money=+(state.money-p.value).toFixed(1);state.players.push(p);state.market=state.market.filter(x=>x.id!==id);state.activity.unshift(['₽','Подписан новый игрок',`${p.name} присоединился к клубу`,'Сейчас']);save();renderAll();toast(`${p.name} подписан`)}
$('#search').oninput=renderPlayers;$$('#filters button').forEach(b=>b.onclick=()=>{$$('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.pos;renderPlayers()});
$('#formation').onchange=e=>{state.formation=e.target.value;renderPitch();save()};['mentality','pressing','tempo'].forEach(id=>$(`#${id}`).oninput=updateReadiness);$$('.instructions button').forEach(b=>b.onclick=()=>{b.classList.toggle('active');state.instructions=$$('.instructions button.active').map(x=>x.dataset.inst);updateReadiness()});
$('#saveTactics').onclick=()=>{save();toast('Тактика сохранена')};$('#train').onclick=()=>{if(state.trained)return toast('Сегодня тренировка уже проведена');state.players.forEach(p=>{p.energy=Math.max(65,p.energy-4);if(Math.random()<.28)p.rating=Math.min(90,p.rating+1)});state.trained=true;state.activity.unshift(['↗','Тренировка завершена','Игроки улучшили форму и связи','Сейчас']);save();renderAll();toast('Тренировка завершена')};
$('#auto').onclick=()=>{state.formation=state.players.filter(p=>posGroup(p.position)==='MID').reduce((s,p)=>s+p.rating,0)>state.players.filter(p=>posGroup(p.position)==='DEF').reduce((s,p)=>s+p.rating,0)?'4-3-3':'3-5-2';renderPitch();save();toast(`Выбрана схема ${state.formation}`)};
$('#refresh').onclick=()=>{if(state.money<.25)return toast('Недостаточно средств');state.money=+(state.money-.25).toFixed(2);generateMarket();renderAll();toast('Рынок обновлён')};
$('#reset').onclick=()=>{if(confirm('Начать новую карьеру?')){localStorage.removeItem(KEY);state=defaults();match=createMatch();renderAll();resetMatch();toast('Новая карьера создана')}};
function createMatch(){return{minute:0,home:0,away:0,homeShots:0,awayShots:0,homeTarget:0,awayTarget:0,pos:50,running:false,paused:false,speed:1,events:[],players:[]}}
function resetMatch(){$('#score').textContent='0 : 0';$('#homeScore').textContent=0;$('#awayScore').textContent=0;$('#clock').textContent='00:00';$('#status').textContent='Матч ещё не начался';$('#shots').textContent='0 — 0';$('#target').textContent='0 — 0';$('#possession').textContent='50% — 50%';$('#commentary').innerHTML='<p>Здесь появятся ключевые события.</p>';$('#start').disabled=false;$('#start').textContent='Начать матч';$('#pause').disabled=true;draw(false)}
function event(text){match.events.unshift(`<p><b>${Math.min(90,Math.floor(match.minute))}'</b>${text}</p>`);$('#commentary').innerHTML=match.events.slice(0,12).join('')}
function simulate(){const attack=.47+(state.mentality-50)/240+(state.tempo-50)/450;if(Math.random()<.12){const home=Math.random()<attack;if(home)match.homeShots++;else match.awayShots++;const target=Math.random()<.56;if(target){home?match.homeTarget++:match.awayTarget++;if(Math.random()<.25){home?match.home++:match.away++;event(`ГОЛ! ${home?'Аврора':'Вектор'} завершает быструю атаку.`)}else event(`${home?'Аврора':'Вектор'} бьёт в створ — вратарь спасает.`)}else event(`${home?'Аврора':'Вектор'} наносит неточный удар.`)}match.pos=Math.max(38,Math.min(66,Math.round(50+(state.pressing-50)/7+(Math.random()-.5)*8)));updateMatchUi()}
function updateMatchUi(){$('#homeScore').textContent=match.home;$('#awayScore').textContent=match.away;$('#score').textContent=`${match.home} : ${match.away}`;$('#clock').textContent=`${String(Math.min(90,Math.floor(match.minute))).padStart(2,'0')}:${String(Math.floor(match.minute%1*60)).padStart(2,'0')}`;$('#shots').textContent=`${match.homeShots} — ${match.awayShots}`;$('#target').textContent=`${match.homeTarget} — ${match.awayTarget}`;$('#possession').textContent=`${match.pos}% — ${100-match.pos}%`}
function startMatch(){if(match.running)return;match=createMatch();match.running=true;$('#start').disabled=true;$('#pause').disabled=false;$('#status').textContent='Матч идёт';event('Стартовый свисток. Аврора начинает с центра поля.');loop();draw(true)}
function loop(){clearInterval(timer);timer=setInterval(()=>{if(match.paused)return;match.minute+=.45*match.speed;simulate();if(match.minute>=90)finish()},450)}
function finish(){match.running=false;clearInterval(timer);cancelAnimationFrame(raf);match.minute=90;updateMatchUi();$('#status').textContent=match.home>match.away?'Победа «Авроры»':match.home===match.away?'Матч завершён вничью':'Поражение «Авроры»';$('#start').disabled=false;$('#start').textContent='Новый матч';$('#pause').disabled=true;const win=match.home>match.away,drawn=match.home===match.away;state.money=+(state.money+(win?1.4:drawn?.8:.45)).toFixed(1);state.fans+=win?950:drawn?180:-120;state.rating+=win?24:drawn?4:-13;state.players.forEach(p=>p.energy=Math.max(55,p.energy-5-Math.floor(Math.random()*8)));state.activity.unshift([win?'★':'◉',win?'Победа в чемпионате':drawn?'Боевая ничья':'Матч завершён',`Аврора ${match.home}:${match.away} Вектор`,'Сейчас']);save();renderAll();event('Финальный свисток. Матч завершён.');toast(`Матч завершён ${match.home}:${match.away}`)}
$('#start').onclick=startMatch;$('#pause').onclick=()=>{if(!match.running)return;match.paused=!match.paused;$('#pause').textContent=match.paused?'Продолжить':'Пауза';$('#status').textContent=match.paused?'Матч приостановлен':'Матч идёт'};$('#speed').onclick=()=>{match.speed=match.speed===1?2:match.speed===2?4:1;$('#speed').textContent=`Скорость ×${match.speed}`;if(match.running)loop()};$('#skip').onclick=()=>{if(!match.running)startMatch();while(match.minute<90){match.minute+=2;simulate()}finish()};
function draw(animate){const c=$('#canvas');if(!c)return;const x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#187a46');g.addColorStop(1,'#0d5c35');x.fillStyle=g;x.fillRect(0,0,w,h);for(let i=0;i<10;i++){x.fillStyle=i%2?'rgba(255,255,255,.018)':'rgba(0,0,0,.025)';x.fillRect(i*w/10,0,w/10,h)}x.strokeStyle='rgba(255,255,255,.48)';x.lineWidth=2;x.strokeRect(22,22,w-44,h-44);x.beginPath();x.moveTo(w/2,22);x.lineTo(w/2,h-22);x.stroke();x.beginPath();x.arc(w/2,h/2,70,0,Math.PI*2);x.stroke();x.strokeRect(22,h/2-105,145,210);x.strokeRect(w-167,h/2-105,145,210);if(!match.players.length)match.players=Array.from({length:22},(_,i)=>({x:i<11?145+Math.random()*300:515+Math.random()*300,y:65+Math.random()*430,vx:(Math.random()-.5)*.8,vy:(Math.random()-.5)*.8}));match.players.forEach((p,i)=>{if(animate&&match.running&&!match.paused){p.x+=p.vx*match.speed;p.y+=p.vy*match.speed;if(p.x<38||p.x>w-38)p.vx*=-1;if(p.y<38||p.y>h-38)p.vy*=-1}x.beginPath();x.arc(p.x,p.y,9,0,Math.PI*2);x.fillStyle=i<11?'#54ef8c':'#e8f0ff';x.shadowColor='rgba(0,0,0,.45)';x.shadowBlur=8;x.fill();x.shadowBlur=0;x.fillStyle=i<11?'#08391b':'#20345b';x.font='700 8px Inter';x.textAlign='center';x.fillText(String(i%11+1),p.x,p.y+3)});const bx=100+(match.minute%15)/15*(w-200),by=h/2+Math.sin(match.minute*.8)*110;x.beginPath();x.arc(bx,by,5,0,Math.PI*2);x.fillStyle='#fff';x.fill();if(animate&&match.running)raf=requestAnimationFrame(()=>draw(true))}
function renderAll(){renderHeader();renderTable();renderActivity();renderPlayers();renderPitch();renderMarket()}
renderAll();resetMatch();window.addEventListener('resize',()=>draw(false));if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
