function bindControls(){
 $('#categoryTabs').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$$('#categoryTabs button').forEach(x=>x.classList.toggle('active',x===b));state.category=b.dataset.category;renderModelList()});
 $('#modelSelect').onchange=e=>{state.model=modelById(e.target.value);renderModelCard()};$('#weatherSelect').onchange=applyEnvironment;$('#timeSelect').onchange=applyEnvironment;
 $('#chooseHomeBtn').onclick=()=>{state.phase='choose-home';$('#chooseHomeBtn').textContent='Нажмите на карту…';setObjective('Укажите место старта на карте',1);$('#hangar').classList.remove('open');toast('Нажмите на нужную точку карты')};$('#launchBtn').onclick=launch;$('#returnBtn').onclick=beginRth;$('#landBtn').onclick=beginLanding;$('#pauseBtn').onclick=togglePause;
 $('#followBtn').onclick=()=>{state.follow=!state.follow;$('#followBtn').textContent=`◎ Слежение: ${state.follow?'вкл.':'выкл.'}`;toast(state.follow?'Слежение включено':'Карта разблокирована')};
 $('#centerBtn').onclick=()=>{state.map.offsetX=state.home.x;state.map.offsetY=state.home.y;renderTiles()};$('#zoomInBtn').onclick=()=>changeZoom(1);$('#zoomOutBtn').onclick=()=>changeZoom(-1);
 $('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#soundBtn').onclick=toggleSound;$('#fullscreenBtn').onclick=toggleFullscreen;$('#menuBtn').onclick=()=>$('#hangar').classList.add('open');$('#closeHangar').onclick=()=>$('#hangar').classList.remove('open');$('#newFlightBtn').onclick=()=>setTimeout(()=>resetFlight(true),0);
 document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();state.keys.add(e.code);if(e.code==='Space'&&!state.launched)launch();if(e.code==='KeyR')beginRth();if(e.code==='KeyL')beginLanding();if(e.code==='KeyP')togglePause()});document.addEventListener('keyup',e=>state.keys.delete(e.code));
 $$('.touch-controls button').forEach(btn=>{const map={left:'ArrowLeft',right:'ArrowRight',up:'ArrowUp',down:'ArrowDown',more:'KeyW',less:'KeyS'},code=map[btn.dataset.control];const on=e=>{e.preventDefault();state.keys.add(code);btn.classList.add('active')},off=e=>{e.preventDefault();state.keys.delete(code);btn.classList.remove('active')};btn.addEventListener('pointerdown',on);btn.addEventListener('pointerup',off);btn.addEventListener('pointercancel',off);btn.addEventListener('pointerleave',off)});
 const map=$('#map');let dragStart=null;
 map.addEventListener('pointerdown',e=>{if(state.phase==='choose-home'){setHomeFromScreen(e.clientX,e.clientY);state.phase='setup';$('#chooseHomeBtn').textContent='Изменить место старта';return}if(state.follow&&state.launched)return;dragStart={x:e.clientX,y:e.clientY,ox:state.map.offsetX,oy:state.map.offsetY};map.setPointerCapture(e.pointerId);map.classList.add('dragging')});
 map.addEventListener('pointermove',e=>{if(!dragStart)return;state.map.offsetX=dragStart.ox-(e.clientX-dragStart.x);state.map.offsetY=dragStart.oy-(e.clientY-dragStart.y);renderTiles()});
 map.addEventListener('pointerup',()=>{dragStart=null;map.classList.remove('dragging')});map.addEventListener('wheel',e=>{e.preventDefault();changeZoom(e.deltaY<0?1:-1)},{passive:false});
 window.addEventListener('resize',resizeCanvas);
}
function changeZoom(delta){const next=clamp(state.map.zoom+delta,11,17);if(next===state.map.zoom)return;const factor=Math.pow(2,next-state.map.zoom);state.map.offsetX*=factor;state.map.offsetY*=factor;state.x*=factor;state.y*=factor;state.home.x*=factor;state.home.y*=factor;state.gates.forEach(g=>{g.x*=factor;g.y*=factor});state.route.forEach(p=>{p.x*=factor;p.y*=factor});state.map.zoom=next;renderTiles();toast(`Масштаб: ${next}`)}

function init(){renderModelList();bindControls();applyEnvironment();resizeCanvas();resetFlight(false);setTimeout(()=>$('#boot').classList.add('hidden'),650);setTimeout(()=>{if(!storageGet('aurora-uav-help')){$('#helpDialog').showModal();storageSet('aurora-uav-help','1')}},900)}
init();
